CREATE TABLE tb_customers (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    middle_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(65) NOT NULL,
    document VARCHAR(55) NOT NULL,
    email VARCHAR(125) NOT NULL,
    telephone VARCHAR(35) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);