CREATE TABLE tb_clients (
id SERIAL PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
middle_name VARCHAR(50) NOT NULL,
last_name VARCHAR(65) NOT NULL,
document VARCHAR(40) NOT NULL UNIQUE,
email VARCHAR(40) NOT NULL UNIQUE,
telephone VARCHAR(35) NOT NULL UNIQUE,
created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);